config/routes.rb
Rails.application.routes.draw do
  resources :educations

  get 'aes_actions/quickedit'
  patch 'aes_actions/quickupdate'

  patch 'materials/quickupdate'
  get 'materials/quickedit'

  patch 'curriculums/quickupdatecategories'
  get 'curriculums/quickeditcategories'

  patch 'curriculums/quickupdate'
  get 'curriculums/quickedit'

  get 'work_experiences/update_levels'
  resources :work_experiences

  match 'actions/:id', to: 'aes_actions#show', via: [:get],  as: 'aes_action_show'
  resources :materials
  get 'users/about'
  match 'about/:id', to: 'users#about', via: [:get],  as: 'about'
  get 'users/show'
  post 'users/send_mail'

  get 'users/changepassword'
  post 'users/changepassword'

  get 'roadmap/get_more_roadmap'
  get 'roadmap/index'
  post 'roadmap/create'
  post 'roadmap/delete'
  post 'roadmap/update'
  get 'roadmap/update_levels'

  get '/comments/get_more_comments'
  get 'comments/index'


  get 'comments/new'

  get 'comments/create'
  post 'comments/create'

  get 'comments/reply'
  post 'comments/reply'




  get 'comment/update'

  get 'comment/destroy'

  get 'home/error'

  get 'curriculums/get_material_types'
  get 'curriculums/update_content'
  get 'curriculums/getlevel'
  resources :aes_actions
  resources :materials
  resources :curriculums
  match 'curriculums/join/:id', to: 'curriculums#join', via: [:get],  as: 'join_curriculum'
  match 'curriculums/comment/:id', to: 'curriculums#comment', via: [:get],  as: 'comments_curriculum'
  match 'curriculums/materials/:id', to: 'curriculums#materials', via: [:get],  as: 'materials_curriculum'
  match 'curriculums/actions/:id', to: 'curriculums#actions', via: [:get],  as: 'actions_curriculum'
  match 'curriculums/mentordetail/:id', to: 'curriculums#show_for_mentor', via: [:get],  as: 'show_curriculum_for_mentor'

  get 'student/update_curriculum_detail', as: 'update_curriculum_detail'
  get 'student/update_menu_right', as: 'update_menu_right'
  match 'student/curriculum-detail/:id', to: 'student#show', via: [:get],  as: 'show_curriculum_detail_for_student'

  get 'mentor/update_curriculum_detail', as: 'mentor_update_curriculum_detail'
  match 'mentor/curriculum-detail/:id', to: 'mentor#show', via: [:get],  as: 'show_curriculum_detail_for_mentor'


  get 'home/index'

  get 'mentor/index'
  get 'student/index'
  get 'mentor/create'

  get 'search/index'
  get 'search/search_curriculum'
  get 'search/update_levels', as: 'update_levels'
  match 'search-curriculum', :to => 'search#search_curriculum', :via => [:get], :as => 'search-curriculum'

  match 'signup', :to => 'sessions#signup', :via => [:get, :post], :as => 'signup'
  match 'signin', :to => 'sessions#signin', :via => [:get, :post], :as => 'signin'
  match 'signout', :to => 'sessions#signout', :via => [:get, :post], :as => 'signout'
  match 'welcome', :to => 'home#welcome', :via =>[:get], :as => 'welcome'
  match 'about-us', :to => 'home#about_us', :via =>[:get], :as => 'about_us'
  match 'home', :to => 'home#index', :via => [:get], :as => 'home'

  match 'become_mentor', :to => 'student#become_mentor', :via => [:get, :post], :as => 'become_mentor'



  get 'sessions/signin'

  get 'sessions/signup'

  get 'sessions/signout'



  root 'sessions#signin'

  get '/auth/:provider/callback', to: 'sns_sessions#create'
  get '/auth/failure', to: redirect('/')
  get 'sns_sessions/create'

  match 'signup_sns', :to => 'sns_sessions#signup_sns', :via => [:get, :post], :as => 'signup_sns'
  get 'sns_sessions/signup_sns'

  get 'sns_sessions/signin_sns'

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all










end

app/models/work_experience.rb
# Class Name: WorkExperience
# Description: work experience model class
# Version: 1.0
# Copyright: Telsoft
# Author: HuyenDT
# Create Date: 18/12/2014
# Modify Date:

class WorkExperience
  include Mongoid::Document
  include Mongoid::Timestamps

  WORK_PLACE_MAX_LENGTH = 200
  DESCRIPTION_MAX_LENGTH = 200

  #fields
  field :work_place, type: String
  field :start_year, type: Integer
  field :end_year, type: Integer
  field :current, type: Boolean
  field :description, type: String

  #relations
  belongs_to :user
  belongs_to :category
  belongs_to :level

  #indexs
  index({user_id: 1})

  #validates
  validates_length_of :work_place, maximum: WORK_PLACE_MAX_LENGTH

  validates_presence_of :category, :level, :user
  validates_presence_of :start_year
  validates_numericality_of :start_year, only_integer: true, greater_than_or_equal_to: 1905, less_than_or_equal_to: Time.now.year
  validates_numericality_of :end_year, only_integer: true, greater_than_or_equal_to: 1905, less_than_or_equal_to: Time.now.year, allow_blank: true

  validates_length_of :description, maximum: DESCRIPTION_MAX_LENGTH

  validate :validate_years

  def validate_years
    # if !self.end_year.nil? && !self.start_year.nil? && self.end_year < self.start_year
    #   errors.add(:end_year, :greater_than_start_date, :count => 1)
    # end
    #

    #
    # if self.current && !self.end_year.nil? && self.end_year < Time.now.year
    #   errors.add(:end_year, :greater_than_or_equal_current_date, :count => 1)
    # end

    if self.current
      self.end_year = nil
    end

    #check start year
    # if !self.start_year.nil?
    #   if self.start_year < 1905
    #     errors.add(:start_year, :greater_than_or_equal_to, :count => 1905)
    #   end
    #
    #   if self.start_year > Time.now.year
    #     errors.add(:start_year, :less_than_or_equal_to, :count => Time.now.year)
    #   end
    # end
    #
    # #check end year
    # if !self.end_year.nil?
    #   if self.end_year < 1905
    #     errors.add(:end_year, :greater_than_or_equal_to, :count => 1905)
    #   end
    #
    #   if self.end_year > Time.now.year
    #     errors.add(:end_year, :less_than_or_equal_to, :count => Time.now.year)
    #   end
    # end


    if !self.start_year.nil? && !self.end_year.nil? && end_year < start_year
      errors.add(:end_year, :greater_than_or_equal_to, :count => self.start_year)
    end

  end
end


app/controllers/work_experiences_controller.rb
class WorkExperiencesController < ApplicationController
  layout 'default'
  before_action :authenticate
  before_action :set_work_experience, only: [:show, :edit, :update, :destroy]

  # GET /work_experiences
  # GET /work_experiences.json
  def index
    user_id = session[:user_id]
    @work_experiences = WorkExperience.where(user_id: user_id).order_by(created_at: -1)
  end

  # GET /work_experiences/1
  # GET /work_experiences/1.json
  def show
  end

  # GET /work_experiences/new
  def new
    @work_experience = WorkExperience.new
  end

  # GET /work_experiences/1/edit
  def edit
    if @work_experience.nil?
      flash.now[:error] = t('work_experiences.msg_work_experience_not_found')
      respond_to do |format|
        format.js { render action: 'edit_fail', :not_found => true }
      end
    end
  end

  # POST /work_experiences
  # POST /work_experiences.json
  def create
    begin
      @work_experience = WorkExperience.new(work_experience_params)
      @work_experience.user_id = session[:user_id]

      respond_to do |format|
        if @work_experience.save
          flash.now[:notice] = t('work_experiences.msg_create_successfully')
          format.html { redirect_to @work_experience, notice: t('work_experiences.msg_create_successfully') }
          format.json { render :show, status: :created, location: @work_experience }
          format.js
        else
          if @work_experience.errors
            flash.now[:error] = @work_experience.errors.full_messages.to_sentence(:last_word_connector => ', ');
          else
            flash.now[:error] = t('work_experiences.msg_create_fail')
          end
          format.html { render :new }
          format.json { render json: @work_experience.errors, status: :unprocessable_entity }
          format.js { render action: 'create_fail' }
        end
      end
    rescue Exception => e
      logger.error("work_experience save error: #{e.message}")
      respond_to do |format|
        flash.now[:error] = t('work_experiences.msg_create_fail')
        format.js { render action: 'create_fail' }
        format.html
      end
    end
  end

  # PATCH/PUT /work_experiences/1
  # PATCH/PUT /work_experiences/1.json
  def update
    if @work_experience.nil?
      flash.now[:error] = t('work_experiences.msg_work_experience_not_found')
      respond_to do |format|
        format.js { render action: 'update_fail' }
      end
    else
      respond_to do |format|
        if @work_experience.update(work_experience_params)
          format.html { redirect_to @work_experience, notice: t('work_experiences.msg_update_successfully')}
          format.json { render :show, status: :ok, location: @work_experience }
          format.js
        else
          if @work_experience.errors
            flash.now[:error] = @work_experience.errors.full_messages.to_sentence(:last_word_connector => ', ');
          else
            flash.now[:error] = t('work_experiences.msg_update_fail')
          end
          format.html { render :edit }
          format.json { render json: @work_experience.errors, status: :unprocessable_entity }
          format.js { render action: 'update_fail' }
        end
      end
    end
  end

  # DELETE /work_experiences/1
  # DELETE /work_experiences/1.json
  def destroy
    if @work_experience.nil?
      flash.now[:error] = t('work_experiences.msg_work_experience_not_found')
      respond_to do |format|
        format.js {render action: 'destroy_fail'}
      end
    else
      if @work_experience.destroy
        respond_to do |format|
          format.html { redirect_to work_experiences_url, notice: t('work_experiences.msg_delete_successfully') }
          format.json { head :no_content }
          format.js
        end
      else
        if @work_experience.errors
          flash.now[:error] = @work_experience.errors.full_messages.to_sentence(:last_word_connector => ', ');
        else
          flash.now[:error] = t('work_experiences.msg_update_fail')
        end

        respond_to do |format|
          format.js {render action: 'destroy_fail'}
        end
      end
    end
  end

  # Description: This method processes get levels by category
  # @param
  # @return
  # @throws Exception
  # @author HuyenDT
  def update_levels
    @levels = Level.where(category_id: params[:category_id]).order_by(level_order: 1)
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_experience
      @work_experience = WorkExperience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_experience_params
      if params[:work_experience][:work_place]
        params[:work_experience][:work_place] = params[:work_experience][:work_place].strip
      end

      if params[:work_experience][:description]
        params[:work_experience][:description] = params[:work_experience][:description].strip
      end

      params.require(:work_experience).permit(:category_id, :level_id, :work_place, :start_year, :end_year, :current, :description)
    end

end

app/helpers/work_experiences_helper.rb
module WorkExperiencesHelper
end

app/views/work_experiences/_form_work_experience.html.erb
<%= form_for @work_experience, html: {id: 'work_experience_form', role: 'form'} do |f| %>
    <div class="widget ">
      <div class="widget-body">
        <div id="panelworkexperience" class="innerLR">
          <div class="workexperience" id="<%= @work_experience.id %>">
            <div class="form-group">
                <%= f.collection_select :category_id, Category.get_all_categories, :id, :category_name, {:include_blank =>  t('work_experiences.placeholder_category')}, {class: 'form-control'} %>
            </div>

            <div class="form-group">
                <%= f.collection_select :level_id, Level.where(category_id: @work_experience.category_id).order_by(level_order: 1), :id, :level_name, {:include_blank =>  t('work_experiences.placeholder_level')}, {class: 'form-control'} %>
            </div>

            <div class="form-group">
                <div class="checkbox">
                  <label class="checkbox-custom">
                    <%= f.check_box :current%><i class="fa fa-fw fa-square-o" style="margin-left: -13px;"></i> <%= t('work_experiences.lb_current') %>
                  </label>
                </div>
            </div>

            <div class="form-group">
              <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                  <%= f.select :start_year, year_options_for_select, {:include_blank => t('work_experiences.placeholder_start_year')}, {class: "form-control"} %>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6">
                  <%= f.select :end_year, year_options_for_select, {:include_blank => t('work_experiences.placeholder_end_year')},  {class: "form-control"}%>
                </div>
              </div>
            </div>


            <div class="form-group">
                <%= f.text_field :work_place, maxlength: 200, class: "form-control", placeholder: t('work_experiences.placeholder_work_place') %>
            </div>

            <div class="form-group">
                <%= f.text_area :description, maxlength: 200, class: 'form-control', placeholder: t('work_experiences.placeholder_description'), rows: 2 %>
            </div>
        </div>
      </div>
    </div>
    </div>

<% end %>

<script>
    $(document).ready(function () {
        $("#work_experience_category_id").change(function () {
            $.ajax('/work_experiences/update_levels', {
                type: 'GET',
                dataType: 'script',
                data: {
                    category_id: $("#work_experience_category_id option:selected").val()
                },
                beforeSend: function (xhr) {
                    $.loader.open({imgUrl: "<%= asset_path('assets/template/ajaxloader/images/loading16x16.gif') %>"});
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    $.loader.close(true);
                    console.log("AJAX Error: " + textStatus);
                },
                success: function (data, textStatus, jqXHR) {
                    $.loader.close(true);
                }
            });
        });

        $('.checkbox-custom > input[type=checkbox]').each(function () {
            var $this = $(this);
            if ($this.data('checkbox')) return;
            $this.checkbox($this.data());
        });

        if ($("#work_experience_current").attr('checked') == 'checked') {
            $("#work_experience_end_year").val('');
            $("#work_experience_end_year").prop('disabled',true);
        }

        $("#work_experience_current").change(function() {
            if(this.checked) {
                $("#work_experience_end_year").val('');
                $("#work_experience_end_year").prop('disabled',true);
            } else {
                $("#work_experience_end_year").prop('disabled',false);
            }
        });

    });
</script>

app/views/work_experiences/_levels.html.erb
<% if @levels %>
    <option value=""><%= t('search_curriculum.placeholder_level') %></option>
    <% @levels.each do |level| %>
        <option value="<%= level.id %>"><%= level.level_name.titleize %></option>
    <% end %>
<% end %>

app/views/work_experiences/_my_work_experience.html.erb
<div class="innerLR">
  <div class="widget">
    <div class="widget-body padding-none">
      <h4 class="innerAll bg-primary text-white margin-bottom-none">Choose Category:</h4>
      <ul class="list-group list-group-1 margin-none borders-none">
        <li class="list-group-item border-top-none"><a href="courses_listing.html?lang=en"><span class="badge pull-right bg-primary ">30</span><i class="fa fa-exclamation-circle"></i>&nbsp; HTML 5</a></li>
        <li class="list-group-item"><a href="courses_listing.html?lang=en"><span class="badge pull-right bg-primary ">2</span><i class="fa fa-ticket"></i>&nbsp; CSS/LESS</a></li>
        <li class="list-group-item"><a href="courses_listing.html?lang=en"><i class="fa fa-spinner"></i>&nbsp; Adobe Photoshop</a></li>
        <li class="list-group-item"><a href="courses_listing.html?lang=en"><i class="fa fa-pencil"></i>&nbsp; PHP</a></li>
        <li class="list-group-item"><a href="courses_listing.html?lang=en"><i class="icon-folder-fill"></i>&nbsp; MYSQL</a></li>
      </ul>
    </div>
  </div>
  <div class="widget">

    <div class="widget-head">
      <h4 class="heading">Work Experience</h4>
    </div>

    <div class="widget-body padding-none">

      <div class="innerAll border-bottom tickets">
        <div class="row">

          <div class="col-sm-10">
            <ul class="media-list margin-none">
              <li class="media">

                <a class="pull-left innerAll half " href="#">
                  <span class="empty-photo"><i class="fa fa-folder fa-2x text-muted"></i></span>
                </a>
                <div class="media-body innerAll half">
                  <a class="media-heading" href="support_answers.html?lang=en">Finding the right team?</a>

                  <label class="label label-default"><a class="user-ticket-action" href="">Unread</a></label>
                  <div class="clearfix"></div>
                  <small>posted by <a href="">Suzanne Marie</a> <i class="fa fa-fw icon-time-clock"></i> 12:51 AM</small>
                </div>
              </li>
            </ul>

          </div>
          <div class="col-sm-2">
            <div class="innerT half pull-right">
              <a class="btn btn-info btn-xs strong" href=""><i class=" icon-comment-fill-1"></i> 3</a>
            </div>
          </div>
        </div>
      </div>

    </div>

  </div>

</div>
</div>

app/views/work_experiences/_work_experience.html.erb
<div class="innerAll border-bottom" id="workexperience<%= work_experience.id %>" data-id="<%= work_experience.id %>">
  <div class="row">
    <div class="col-sm-10">
      <ul class="media-list margin-none">
        <li class="media">

          <span class="pull-left innerAll half empty-photo"><i class="fa fa-briefcase fa-2x text-muted"></i></span>

          <div class="media-body innerAll half">
            <span class="media-heading aes-color"><%= work_experience.category.category_name%></span>
            <br/>
            <small><%= work_experience.level.level_name%></small>
            <br/>


            <% if work_experience.end_year && !work_experience.end_year.nil?%>
                <small><i class="fa fa-calendar"></i> <%=work_experience.start_year%> - <%=work_experience.end_year%></small>
            <% else %>
                <small><i class="fa fa-calendar"></i> <%=work_experience.start_year%> - <%=t("work_experiences.lb_current")%></small>
            <% end %>

            <br/>
            <% if work_experience.work_place && !work_experience.work_place.empty? %>
                <small style="word-wrap: break-word;"><%=t('work_experiences.lb_work_place')%>: <%= work_experience.work_place%></small>
            <% else %>
                <small><%=t('work_experiences.lb_work_place')%>: NA</small>
            <% end %>

            <br/>

            <% if work_experience.description && !work_experience.description.empty? %>
                <small style="word-wrap: break-word;"><%=t('work_experiences.lb_description')%>: <%= work_experience.description%></small>
            <% else %>
                <small><%=t('work_experiences.lb_description')%>: NA</small>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
    <div class="col-sm-2">
      <div class="innerT half pull-right">
        <a class="editWorkExperience btn btn-xs btn-primary" url="<%= edit_work_experience_path(work_experience) %>" objectId="<%= work_experience.id%>" href="#" data-toggle="modal"  modal_title="<%=t('work_experiences.title_edit_work_experience')%>"><i class="fa fa-pencil fa-fw"></i></a>
        <a class="deleteWorkExperience btn btn-xs btn-primary" url="<%= work_experience_path(work_experience) %>" href="#" data-toggle="modal"  modal_title="<%=t('work_experiences.title_delete_work_experience')%>" title_confirm="<%=t('work_experiences.title_confirm_delete_work_experience')%>" title_msg_confirm="<%=t('work_experiences.msg_confirm_delete_work_experience')%>" title_button_ok="<%=t('button.btn_ok')%>" title_button_cancel="<%=t('button.btn_cancel')%>"><i class="fa fa-times fa-fw"></i></a>
      </div>
    </div>
  </div>
</div>

app/views/work_experiences/create_fail.js.erb
$.gritter.add({
    title: '<%= t('system.system_message') %>',
    text: '<%= flash[:error]%>',
    before_open: function(){
        if($('.gritter-item-wrapper').length == 1)
        {
            return false;
        }
    }
});

app/views/work_experiences/destroy.js.erb
$('#workexperience<%= @work_experience.id %>').remove();

app/views/work_experiences/destroy_fail.js.erb
$.gritter.add({
    title: '<%= t('system.system_message') %>',
    text: '<%= flash[:error]%>',
    before_open: function(){
        if($('.gritter-item-wrapper').length == 1)
        {
            return false;
        }
    }
});

app/views/work_experiences/edit.html.erb
<h1>Editing work_experience</h1>

<%= render 'form' %>

<%= link_to 'Show', @work_experience %> |
<%= link_to 'Back', work_experiences_path %>

app/views/work_experiences/edit.js.erb
$('#modalContent').html('<%= escape_javascript(render(:partial  => 'work_experiences/form_work_experience', locals: {work_experience: @work_experience})) %>')
$('#workExperienceModal').modal({backdrop: 'static', keyboard: false});

app/views/work_experiences/index_bk.html.erb
<div class="innerLR">

  <div class="widget">

    <div class="widget-head">
      <h4 class="heading">Work Experience</h4>
    </div>

    <div class="widget-body padding-none">

      <div class="innerAll border-bottom tickets">
        <div class="row">

          <div class="col-sm-10">
            <ul class="media-list margin-none">
              <li class="media">

                <a class="pull-left innerAll half " href="#">
                  <span class="empty-photo"><i class="fa fa-folder fa-2x text-muted"></i></span>
                </a>
                <div class="media-body innerAll half">
                  <a class="media-heading" href="support_answers.html?lang=en">Finding the right team?</a>

                  <label class="label label-default"><a class="user-ticket-action" href="">Unread</a></label>
                  <div class="clearfix"></div>
                  <small>posted by <a href="">Suzanne Marie</a> <i class="fa fa-fw icon-time-clock"></i> 12:51 AM</small>
                </div>
              </li>
            </ul>

          </div>
          <div class="col-sm-2">
            <div class="innerT half pull-right">
              <a class="btn btn-info btn-xs strong" href=""><i class=" icon-comment-fill-1"></i> 3</a>
            </div>
          </div>
        </div>
      </div>

    </div>

  </div>

</div>
</div>

app/views/work_experiences/new.js.erb
$('#modalContent').html('<%= escape_javascript(render(:partial  => 'work_experiences/form_work_experience', locals: {work_experience: @work_experience})) %>')

app/views/work_experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @work_experience.user.id %>
</p>


<p>
  <strong>Category:</strong>
  <%= @work_experience.category.id %>
</p>

<p>
  <strong>Level:</strong>
  <%= @work_experience.level.id %>
</p>

<p>
  <strong>Work place:</strong>
  <%= @work_experience.work_place %>
</p>

<p>
  <strong>From year:</strong>
  <%= @work_experience.start_year %>
</p>

<p>
  <strong>To year:</strong>
  <%= @work_experience.end_year %>
</p>

<p>
  <strong>Current:</strong>
  <%= @work_experience.current %>
</p>

<p>
  <strong>Description:</strong>
  <%= @work_experience.description %>
</p>

<%= link_to 'Edit', edit_work_experience_path(@work_experience) %> |
<%= link_to 'Back', work_experiences_path %>

app/views/work_experiences/update.js.erb
$('#workexperience<%= @work_experience.id %>').replaceWith('<%= escape_javascript(render partial: @work_experience) %>');
//notyfy({
//    text: '<%= flash[:notice]%>',
//    type: 'alert',
//    dismissQueue: false,
//    layout: 'top',
//    timeout: 5000 // delay for closing event. Set false for sticky notifications
//});
$('#workExperienceModal').modal('hide');

var editElement = $('#workexperience<%= @work_experience.id %>').find(".editWorkExperience");
$(editElement).bind('click', function (e) {
    openEditWorkExperienceModal(this, e)
});

var deleteElement = $('#workexperience<%= @work_experience.id %>').find(".deleteWorkExperience");
$(deleteElement).bind('click', function (e) {
    processDeleteWorkExperience(this, e);
});

app/views/work_experiences/update_fail.js.erb
$.gritter.add({
    title: '<%= t('system.system_message') %>',
    text: '<%= flash[:error]%>',
    before_open: function(){
        if($('.gritter-item-wrapper').length == 1)
        {
            return false;
        }
    }
});