config/routes.rb
Rails.application.routes.draw do
  resources :educations

  get 'aes_actions/quickedit'
  patch 'aes_actions/quickupdate'

  patch 'materials/quickupdate'
  get 'materials/quickedit'

  patch 'curriculums/quickupdatecategories'
  get 'curriculums/quickeditcategories'

  patch 'curriculums/quickupdate'
  get 'curriculums/quickedit'

  get 'work_experiences/update_levels'
  resources :work_experiences

  match 'actions/:id', to: 'aes_actions#show', via: [:get],  as: 'aes_action_show'
  resources :materials
  get 'users/about'
  match 'about/:id', to: 'users#about', via: [:get],  as: 'about'
  get 'users/show'
  post 'users/send_mail'

  get 'users/changepassword'
  post 'users/changepassword'

  get 'roadmap/get_more_roadmap'
  get 'roadmap/index'
  post 'roadmap/create'
  post 'roadmap/delete'
  post 'roadmap/update'
  get 'roadmap/update_levels'

  get '/comments/get_more_comments'
  get 'comments/index'


  get 'comments/new'

  get 'comments/create'
  post 'comments/create'

  get 'comments/reply'
  post 'comments/reply'




  get 'comment/update'

  get 'comment/destroy'

  get 'home/error'

  get 'curriculums/get_material_types'
  get 'curriculums/update_content'
  get 'curriculums/getlevel'
  resources :aes_actions
  resources :materials
  resources :curriculums
  match 'curriculums/join/:id', to: 'curriculums#join', via: [:get],  as: 'join_curriculum'
  match 'curriculums/comment/:id', to: 'curriculums#comment', via: [:get],  as: 'comments_curriculum'
  match 'curriculums/materials/:id', to: 'curriculums#materials', via: [:get],  as: 'materials_curriculum'
  match 'curriculums/actions/:id', to: 'curriculums#actions', via: [:get],  as: 'actions_curriculum'
  match 'curriculums/mentordetail/:id', to: 'curriculums#show_for_mentor', via: [:get],  as: 'show_curriculum_for_mentor'

  get 'student/update_curriculum_detail', as: 'update_curriculum_detail'
  get 'student/update_menu_right', as: 'update_menu_right'
  match 'student/curriculum-detail/:id', to: 'student#show', via: [:get],  as: 'show_curriculum_detail_for_student'

  get 'mentor/update_curriculum_detail', as: 'mentor_update_curriculum_detail'
  match 'mentor/curriculum-detail/:id', to: 'mentor#show', via: [:get],  as: 'show_curriculum_detail_for_mentor'


  get 'home/index'

  get 'mentor/index'
  get 'student/index'
  get 'mentor/create'

  get 'search/index'
  get 'search/search_curriculum'
  get 'search/update_levels', as: 'update_levels'
  match 'search-curriculum', :to => 'search#search_curriculum', :via => [:get], :as => 'search-curriculum'

  match 'signup', :to => 'sessions#signup', :via => [:get, :post], :as => 'signup'
  match 'signin', :to => 'sessions#signin', :via => [:get, :post], :as => 'signin'
  match 'signout', :to => 'sessions#signout', :via => [:get, :post], :as => 'signout'
  match 'welcome', :to => 'home#welcome', :via =>[:get], :as => 'welcome'
  match 'about-us', :to => 'home#about_us', :via =>[:get], :as => 'about_us'
  match 'home', :to => 'home#index', :via => [:get], :as => 'home'

  match 'become_mentor', :to => 'student#become_mentor', :via => [:get, :post], :as => 'become_mentor'



  get 'sessions/signin'

  get 'sessions/signup'

  get 'sessions/signout'



  root 'sessions#signin'

  get '/auth/:provider/callback', to: 'sns_sessions#create'
  get '/auth/failure', to: redirect('/')
  get 'sns_sessions/create'

  match 'signup_sns', :to => 'sns_sessions#signup_sns', :via => [:get, :post], :as => 'signup_sns'
  get 'sns_sessions/signup_sns'

  get 'sns_sessions/signin_sns'

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all










end

app/controllers/mentor_controller.rb
# Class Name: SessionsController
# Description: This class processes functions of mentor
# Version: 1.0
# Copyright: Telsoft
# Author: HuyenDT
# Create Date: 14/10/2014
# Modify Date: 28/10/2014

class MentorController < ApplicationController
  layout 'default'

  before_action :authenticate

  def index
  end
  def create
  end

  # Description: This method processes show curriculum of mentor
  # @param
  # @return
  # @throws Exception
  # @author HuyenDT
  # Create Date: 2014/12/02
  # Modify Date: 2014/12/05

  def show
    @curriculum = Curriculum.find(params[:id])
    if @curriculum
      if @curriculum.mentor.id == current_user.id
        @object = @curriculum

        #get material is root
        @materials = Curriculum.get_root_material(params[:id])

        #get notification of curriculum
        @curriculum_notification = Notification.get_notification_by_object_recipient(Notification::COMMENT_TYPE, Comment::CURRICULUM_TYPE, [@object.id], current_user.id, TRUE)

        #get notification of materials
        material_ids = []
        @curriculum.materials.each do |material|
          material_ids << material.id
        end
        @material_notification = Notification.get_notification_by_object_recipient(Notification::COMMENT_TYPE, Comment::MATERIAL_TYPE, material_ids, current_user.id, TRUE)

        #get notification of actions
        action_ids = []
        @curriculum.actions.each do |action|
          action_ids << action.id
        end
        @action_notification = Notification.get_notification_by_object_recipient(Notification::COMMENT_TYPE, Comment::ACTION_TYPE, action_ids, current_user.id, TRUE)
      else
        flash[:error] = t('msg_access_error')
        redirect_to home_error_path
      end
    else
      flash[:error] = t('curriculums.msg_curriculum_not_found')
      redirect_to home_error_path
    end
  end

  # Description: This method processes update content of curriculum detail: when mentor click Curriculum/Matertial/Action
  # @param
  # @return
  # @throws Exception
  # @author HuyenDT
  # Create Date: 2014/12/02
  # Modify Date: 2014/12/02
  def update_curriculum_detail
    begin
      @object_type = params[:object_type]
      if @object_type == 'curriculum'
        @curriculum_detail = Curriculum.find_by(_id: params[:object_id])
        @object = @curriculum_detail
      elsif @object_type == 'material'
        @material_detail = Material.find_by(_id: params[:object_id])
        @object = @material_detail
      elsif @object_type == 'action'
        @action_detail = Action.find_by(_id: params[:object_id])
        @object = @action_detail
      end

      # update read all notification (new comment)
      current_user.read_all_notification(Notification::COMMENT_TYPE, @object.id, @object.object_type)

      #render response
      respond_to do |format|
        format.js
        format.html
      end
    rescue Exception => e
      logger.error("update_curriculum_detail error: #{e.message}")
      respond_to do |format|
        flash.now[:error] = t('mentor.curriculums.msg_load_detail_fail')
        format.js
        format.html
      end
    end
  end

end

app/helpers/mentor_helper.rb
module MentorHelper
  def render_unread_notification(activity_type, object_id, object_type)
    render_msg = ''
    count = current_user.count_unread_notification(activity_type, object_id, object_type)
    if count > 0
      render_msg += "<span class='badge bg-primary'> #{count} </span>"
    end
    render_msg.html_safe
  end
end

app/views/mentor/_comments.html.erb
<div class="innerAll" >

  <div class="post-block post-comments" style="border-top:0px;margin-top: 10px">
    <!--All comment-->
    <h4 id="comments-count"><%= t('comments.lb_all_comments') %>&#40;<%= @commentable.get_total_comments%>&#41;</h4>
    <!--End all comment-->
    <div class="separator"></div>

    <!--New comment form-->
    <div id="comment-new">
      <%= render partial: 'comments/comment_form', locals: {commentable: @commentable} %>
    </div>
    <!--End new comment form-->
    <div class="separator"></div>

    <!--List comment-->
    <div id="comments-list">
      <%= render @commentable.get_lastest_comments %>
    </div>
    <!--End list comment-->
    <div class="separator"></div>

    <div class="load-more-container">
      <!-- hide our loading gif image so that we show it when making ajax call via jquery -->
      <%= image_tag "ajax-loader.gif", style: "display:none;", class: "loading-gif" %>
      <div class="row">
        <div class="col-md-12">
          <div class="pull-left">
            <button id="load-more" class="btn btn-primary btn-md" type="button"><%= t('comments.btn_load_more')%></button>
            <p id="load-more-error" class="has-error help-block"></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
    $(document).ready(function () {
        $(function () {
            $('form.new-reply').submit(function (e) {
                e.preventDefault();
                var that = this;
                $.ajax({
                    type: "POST",
                    url: "/comments/reply",
                    data: {
                        commentable_id: $(this).find('#commentable_id').val(),
                        commentable_type: $(this).find('#commentable_type').val(),
                        comment: $(this).find("#comment").val(),
                        parent_id: $(this).find("#parent_id").val()
                    },
                    success: function (data) {
                    },
                    error: function (xhr, status, response) {
                        console.log("AJAX Error: " + status)
                    }
                });
            });
        });

        $(function(){
            var total_comments = '<%= @commentable.get_total_comments %>'
            var comments_length = $('.comment').length
            if (comments_length >= total_comments) {
                $('#load-more').hide()
            } else {
                $('#load-more').show();
            }
        });

        $("#load-more").click(function () {
            $('#load-more').hide();
            $('.loading-gif').show();

            var last_id = $('.comment').last().attr('data-id');
            $.ajax({
                type: "GET",
                url: '/comments/get_more_comments',
                data: {
                    last_comment_id: last_id,
                    commentable_id: "<%= @commentable.id%>",
                    commentable_type: "<%= @commentable.commentable_type%>"
                },

                dataType: "script",
                success: function () {
                    $('.loading-gif').hide();
                    bindReplyForm();
                },
                error: function (xhr, status, response) {
                    console.log("AJAX Error: " + status)
                }
            });
        });
    });
</script>

app/views/mentor/_content.html.erb
<p id="load-detail-error" class="has-error help-block"><%= flash[:error]%></p>
<% if flash[:error].nil? %>
    <%if @object_type=='curriculum'%>
        <% if @curriculum_detail %>
            <p class="pull-right visible-xs">
              <a href="javascript:;" data-toggle="offcanvas" class="no-ajaxify btn-outline"><i class="fa fa-arrow-left"></i></a>
            </p>
            <div style="clear:both; position: relative;">
              <h3 class="aes-color  aes-border-bottom name_update" style="word-wrap: break-word; margin-right: 30px;"><%= @curriculum_detail.curriculum_name %></h3>
              <ul class="nav nav-pills" role="tablist" style="top:0; right: 0px; position: absolute; z-index: 100">
                <li role="presentation" class="dropdown pull-right">
                  <a id="drop6" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="false">
                    <span class="caret"></span>
                  </a>
                  <ul id="menu3" class="dropdown-menu" role="menu" aria-labelledby="drop6">
                    <li role="presentation"><%= link_to '<i class="fa fa-edit"></i> '.html_safe + t('curriculum.bt_edit'), edit_curriculum_path(@curriculum_detail), :title => t('curriculum.bt_edit') %></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" class="quickUpdate" url="<%= curriculums_quickedit_path%>" objectid="<%= @curriculum_detail.id %>" href="#" modal_title="<%= t('curriculum.title_update_curriculum')%>"><i class="fa fa-edit"></i> <%= t('curriculum.title_update_curriculum')%></a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" class="quickUpdate" url="<%= curriculums_quickeditcategories_path %>" objectid="<%= @curriculum_detail.id %>" href="#" modal_title="<%= t('category.title_quick_update')%>" ><i class="fa fa-edit"></i> <%= t('category.title_quick_update')%></a></li>
                    <li role="presentation" class="divider"></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="javascript:;"><%= t('button.btn_close') %></a></li>
                  </ul>
                </li>
              </ul>
              <p class="innerLR half"><span><i class="fa fa-user">&nbsp;</i><%= @curriculum_detail.mentor.user_name %></span>&nbsp;|&nbsp;<span><i class="fa fa-calendar">&nbsp;</i><%= @curriculum_detail.created_at.strftime("%Y/%m/%d") %></span>
              </p>
            </div>
            <!--Categories CuongCT disabled 23-12-2014 -->
            <!--<div class="row box box-transparent">-->
              <!--<% @curriculum_detail.curriculum_categories.each_with_index do |category,index| %>-->
                  <!--<div class="col-xs-4 col-sm-2">-->
                    <!--<div class="box-quick-link color-background<%=index+1%>">-->
                      <!--<a href="javascript:;" >-->
                        <!--<div class="listLevel" style="display: none">-->
                          <!--<ul>-->
                            <!--<% category.levels.each do |level| %>-->
                                <!--<li>-->
                                  <!--<%= level.level_name %>-->
                                <!--</li>-->
                            <!--<% end %>-->
                          <!--</ul>-->
                        <!--</div>-->
                        <!--<div class="header">-->
                          <!--<div class="icon-star"></div>-->
                        <!--</div>-->
                        <!--<div class="content"><%= category.category_name%></div>-->
                      <!--</a>-->
                    <!--</div>-->
                  <!--</div>-->
              <!--<% end %>-->
            <!--</div>-->
            <div class="separator"></div>
            <div id="divDescription" style="position: relative;">
              <div class="innerLR half description_update" style="overflow: auto"><%= @curriculum_detail.description.html_safe %></div>
            </div>
            </div>
        <% end %>
    <%elsif @object_type=='material'%>
        <% if @material_detail %>
            <p class="pull-right visible-xs">
              <a href="javascript:;" data-toggle="offcanvas" class="no-ajaxify btn-outline"><i class="fa fa-arrow-left"></i></a>
            </p>
            <div style="clear:both; position: relative;">
                <h3 class="aes-color aes-border-bottom name_update" style="word-wrap: break-word; margin-right: 30px;"><%=@material_detail.material_name%></h3>
                <ul class="nav nav-pills" role="tablist" style="top:0; right: 0px; position: absolute; z-index: 100">
                  <li role="presentation" class="dropdown pull-right">
                    <a id="drop6" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="false">
                      <span class="caret"></span>
                    </a>
                    <ul id="menu3" class="dropdown-menu" role="menu" aria-labelledby="drop6">
                      <li role="presentation"><a class="quickUpdate" url="<%= materials_quickedit_path %>" objectid="<%= @material_detail.id %>" href="#"  data-toggle="modal" modal_title="<%= t('material.title_quick_update')%>"><i class="fa fa-edit"></i> <%= t('material.title_quick_update')%></a></li>
                      <li role="presentation" class="divider"></li>
                      <li role="presentation"><a role="menuitem" tabindex="-1" href="javascript:;"><%= t('button.btn_close') %></a></li>
                    </ul>
                  </li>
                </ul>
                <!--<a class="quickUpdate" url="/materials" objectid="<%= @material_detail.id %>" href="#"  data-toggle="modal" title="<%= t('material.title_quick_update')%>" style="top:0; right: 0; position: absolute"><i class="fa fa-edit"></i></a>-->
                <!--<h5 class="strong"><%= @material_detail.material_name %></h5>-->
                <p>
                  <span class="strong"><%=t('material.lb_type')%></span>: <span class="type_update"><%=@material_detail.material_type.material_type_name%></span>
                </p>
            </div>
            <div id="div_Url">
                <%if !@material_detail.material_url.nil? && !@material_detail.material_url.empty?%>
                    <p>
                      <span class="strong"><%=t('material.lb_url')%></span>: <a class="url_update" href="<%= @material_detail.material_url%>"><%= @material_detail.material_url%></a>
                    </p>
                <% end %>
            </div>
            <div style="overflow: auto; text-align: justify;" class="description_update"><%= @material_detail.description.html_safe %></div>
        <% end %>
    <%elsif @object_type=='action'%>
        <% if @action_detail %>
            <p class="pull-right visible-xs">
              <a href="javascript:;" data-toggle="offcanvas" class="no-ajaxify btn-outline"><i class="fa fa-arrow-left"></i></a>
            </p>
            <div style="clear:both; position: relative;">
                <h3 class="aes-color aes-border-bottom name_update" style="word-wrap: break-word; margin-right: 30px;"><%= @action_detail.action_name %></h3>
                <ul class="nav nav-pills" role="tablist" style="top:0; right: 0px; position: absolute; z-index: 100">
                    <li role="presentation" class="dropdown pull-right">
                      <a id="drop6" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="false">
                        <span class="caret"></span>
                      </a>
                      <ul id="menu3" class="dropdown-menu" role="menu" aria-labelledby="drop6">
                        <li role="presentation"><a class="quickUpdate" url="<%= aes_actions_quickedit_path %>" objectid="<%= @action_detail.id %>" href="#"  data-toggle="modal" modal_title="<%= t('action.title_quick_update')%>"><i class="fa fa-edit"></i> <%= t('action.title_quick_update')%></a></li>
                        <li role="presentation" class="divider"></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="javascript:;"><%= t('button.btn_close') %></a></li>
                      </ul>
                    </li>
                </ul>
                <div style="overflow: auto; text-align: justify;" class="description_update"><%= sanitize @action_detail.description %></div>
            </div>
        <% end %>
    <% end %>
<% end %>
<script>
    $(document).ready(function () {
        $('.quickUpdate').click( function (e) {
            e.preventDefault();
            var url = $(this).attr("url");
            var id = $(this).attr("objectid");
            var title = $(this).attr("modal_title");
            console.log(id);
            console.log($(this).attr("url"));
            console.log($(this));
            $.ajax({
                type: "GET",
                url: url,
                data: {
                    id: id
                },
                beforeSend: function (xhr) {
                    $.loader.open({size:32});
                },
                dataType: "script",
                success: function () {
                    $.loader.close(true);
                    $('#updateModal').modal();
                    $("#updateModalLabel").text(title);
                },
                error: function (xhr, status, response) {
                    console.log("AJAX Error: " + status)
                    $.loader.close(true);
                }
            });
        });

        $('.btn-outline').click(function () {
            $('.row-offcanvas').toggleClass('active');
            $(this).find("i").toggleClass('fa-arrow-left');
            $(this).find("i").toggleClass('fa-arrow-right');
        });
        $('.box-quick-link a').popover({
            placement: 'auto',
            html: true,
            container: 'body',
            title: function () {
                return $(this).find("div.content").html();
            },
            content: function () {
                return $(this).find("div.listLevel").html();
            }
        });
    });

</script>

app/views/mentor/_error.js.erb
$.gritter.add({
    title: '<%= t('system.system_message') %>',
    text: '<%= flash[:error]%>',
    before_open: function(){
        if($('.gritter-item-wrapper').length == 1)
        {
            return false;
        }
    }
});

app/views/mentor/_success.js.erb
notyfy({
    text: '<%= flash[:notice]%>',
    type: 'alert',
    dismissQueue: false,
    layout: 'top',
    timeout: 5000 // delay for closing event. Set false for sticky notifications
});


$(".name_update").text($(quick_form).find("input.name_update").val());//TODO xem lai type sau khi update
$("div.description_update").html($(quick_form).find("textarea.description_update").val());

if($(quick_form).find("textarea.summary_update").val()!=null){
    $("div.summary_update").html($(quick_form).find("textarea.summary_update").val());
}
if($(quick_form).find("button.selectpicker").val()!=null){
    $("span.type_update").text($(quick_form).find("button.selectpicker").attr("title"));
}
if($(quick_form).find("input.url_update").val()!=null){
    if($(quick_form).find("input.url_update").val().length==0){
        $("#div_Url").empty();
    }else{
        var material_url = $(quick_form).find("input.url_update").val();
        var urltemplate = "<p><span class=\"strong\"><%=t('material.lb_url')%></span>: <a class=\"url_update\" href=\""+material_url+"\">"+material_url+"</a></p>";
        $("#div_Url").html(urltemplate);
    }
}
$('#updateModal').modal('hide');

app/views/mentor/index.html.erb
<% if !current_user.nil? %>
    <h1>Welcome <%= @current_user.user_name %>!</h1>
<% else %>
    <h1>Please login</h1>
<% end %>

app/views/mentor/update_curriculum_detail.js.erb
$("#divContent").html("<%= escape_javascript(render(:partial => 'mentor/content')) %>");
$("#divComments").html("<%= escape_javascript(render(:partial => 'comments/comments')) %>");
$('#load-detail-error').html('')

app/views/mentor/update_curriculum_detail_fail.js.erb
$("#divContent").html("<%= escape_javascript(render(:partial => 'mentor/content')) %>");
$('#load-detail-error').html('<%= flash[:error]%>')