config/routes.rb
Rails.application.routes.draw do
  resources :educations

  get 'aes_actions/quickedit'
  patch 'aes_actions/quickupdate'

  patch 'materials/quickupdate'
  get 'materials/quickedit'

  patch 'curriculums/quickupdatecategories'
  get 'curriculums/quickeditcategories'

  patch 'curriculums/quickupdate'
  get 'curriculums/quickedit'

  get 'work_experiences/update_levels'
  resources :work_experiences

  match 'actions/:id', to: 'aes_actions#show', via: [:get],  as: 'aes_action_show'
  resources :materials
  get 'users/about'
  match 'about/:id', to: 'users#about', via: [:get],  as: 'about'
  get 'users/show'
  post 'users/send_mail'

  get 'users/changepassword'
  post 'users/changepassword'

  get 'roadmap/get_more_roadmap'
  get 'roadmap/index'
  post 'roadmap/create'
  post 'roadmap/delete'
  post 'roadmap/update'
  get 'roadmap/update_levels'

  get '/comments/get_more_comments'
  get 'comments/index'


  get 'comments/new'

  get 'comments/create'
  post 'comments/create'

  get 'comments/reply'
  post 'comments/reply'




  get 'comment/update'

  get 'comment/destroy'

  get 'home/error'

  get 'curriculums/get_material_types'
  get 'curriculums/update_content'
  get 'curriculums/getlevel'
  resources :aes_actions
  resources :materials
  resources :curriculums
  match 'curriculums/join/:id', to: 'curriculums#join', via: [:get],  as: 'join_curriculum'
  match 'curriculums/comment/:id', to: 'curriculums#comment', via: [:get],  as: 'comments_curriculum'
  match 'curriculums/materials/:id', to: 'curriculums#materials', via: [:get],  as: 'materials_curriculum'
  match 'curriculums/actions/:id', to: 'curriculums#actions', via: [:get],  as: 'actions_curriculum'
  match 'curriculums/mentordetail/:id', to: 'curriculums#show_for_mentor', via: [:get],  as: 'show_curriculum_for_mentor'

  get 'student/update_curriculum_detail', as: 'update_curriculum_detail'
  get 'student/update_menu_right', as: 'update_menu_right'
  match 'student/curriculum-detail/:id', to: 'student#show', via: [:get],  as: 'show_curriculum_detail_for_student'

  get 'mentor/update_curriculum_detail', as: 'mentor_update_curriculum_detail'
  match 'mentor/curriculum-detail/:id', to: 'mentor#show', via: [:get],  as: 'show_curriculum_detail_for_mentor'


  get 'home/index'

  get 'mentor/index'
  get 'student/index'
  get 'mentor/create'

  get 'search/index'
  get 'search/search_curriculum'
  get 'search/update_levels', as: 'update_levels'
  match 'search-curriculum', :to => 'search#search_curriculum', :via => [:get], :as => 'search-curriculum'

  match 'signup', :to => 'sessions#signup', :via => [:get, :post], :as => 'signup'
  match 'signin', :to => 'sessions#signin', :via => [:get, :post], :as => 'signin'
  match 'signout', :to => 'sessions#signout', :via => [:get, :post], :as => 'signout'
  match 'welcome', :to => 'home#welcome', :via =>[:get], :as => 'welcome'
  match 'about-us', :to => 'home#about_us', :via =>[:get], :as => 'about_us'
  match 'home', :to => 'home#index', :via => [:get], :as => 'home'

  match 'become_mentor', :to => 'student#become_mentor', :via => [:get, :post], :as => 'become_mentor'



  get 'sessions/signin'

  get 'sessions/signup'

  get 'sessions/signout'



  root 'sessions#signin'

  get '/auth/:provider/callback', to: 'sns_sessions#create'
  get '/auth/failure', to: redirect('/')
  get 'sns_sessions/create'

  match 'signup_sns', :to => 'sns_sessions#signup_sns', :via => [:get, :post], :as => 'signup_sns'
  get 'sns_sessions/signup_sns'

  get 'sns_sessions/signin_sns'

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all










end

app/models/material.rb
# Class Name: Material
# Description: Material model class
# Version: 1.0
# Copyright: Telsoft
# Author: HuyenDT
# Create Date: 06/11/2014
# Modify Date: 06/11/2014

class Material
  include Mongoid::Document
  include Mongoid::Tree
  include Mongoid::Tree::Ordering
  include Mongoid::Timestamps

  #constanst
  NAME_MAX_LENGTH = 100
  URL_MAX_LENGTH = 500
  DESCRIPTION_MAX_LENGTH=10000


  #fields
  field :material_name, type: String
  field :material_url, type:	String
  field :description, type: String
  field :status, type: Integer, default: 1

  #relations
  #belongs_to :parent, class_name: self.name
  belongs_to :material_type
  belongs_to :curriculum

  #attributes
  attr_accessor :state

  #CuongCT 18-11-2014
  #validate
  validates_presence_of :material_name, :material_type
  validates_length_of :material_name, maximum: NAME_MAX_LENGTH
  validates_length_of :description, maximum: DESCRIPTION_MAX_LENGTH
  validates_length_of :material_url, maximum: URL_MAX_LENGTH
  validates_format_of :material_url, :with => URI::regexp(%w(http https)), :allow_blank => true

  #indexes
  index({ material_type_id: 1 })
  index({ curriculum_id: 1 })
  index({ material_name: 1 })

  #validate
  #validates_presence_of :material_name, :curriculum_id, :material_type_id, :status

  def object_type
    self.class.name
  end

  # Description: get lastest comment
  # @param:
  # @return:
  # @throws Exception:
  # @author: HuyenDT
  # Create Date: 01/12/2014
  # Modify Date:
  def get_lastest_comments
    Comment.where(object_id: self.id, object_type: object_type, parent_id: nil).order_by(created_at: -1).limit(Comment::COMMENT_PER_PAGE)
  end

  # Description: get total comment
  # @param:
  # @return:
  # @throws Exception:
  # @author: HuyenDT
  # Create Date: 29/11/2014
  # Modify Date:
  def get_total_comments
    Comment.where(object_id: self.id, object_type: object_type).count()
  end

  def get_total_comments_not_reply
    Comment.where(object_id: self.id, object_type: object_type, parent_id: nil).count()
  end


  def get_author
    self.curriculum.mentor
  end
end

app/models/material_type.rb
# Class Name: MaterialType
# Description: MaterialType model class
# Version: 1.0
# Copyright: Telsoft
# Author: HuyenDT
# Create Date: 06/11/2014
# Modify Date: 06/11/2014

class MaterialType
  include Mongoid::Document
  #fields
  field :material_type_name, type: String
  field :show_priority, type: Integer, default: 1

  #validates
  validates_presence_of :material_type_name, :show_priority
  validates_uniqueness_of :material_type_name

end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  layout 'default'
  before_action :authenticate
  before_filter :mentor_required, only: [:edit, :update]
  skip_before_action :verify_authenticity_token

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
    if @material
      @object=@material
      curriculum_id=@material.curriculum_id
      @curriculum = Curriculum.find(curriculum_id)
      @materials=Curriculum.get_root_material(curriculum_id)
    else
      flash[:error] = t('msg_access_error')
    end
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # Description: This method get materials from params
  # @param
  # @return
  # @throws Exception
  # @author CuongCT
  # Create Date: 2014/12/17
  # Modify Date:
  def quickedit
    # //TODO: checkrole
    material_id = BSON::ObjectId.from_string(params[:id])

    @material = Material.find_by(_id: material_id)
    respond_to do |format|
      format.js {render partial: 'materials/edit'}
      format.html
    end
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # Description: This method update materials to database
  # @param
  # @return
  # @throws Exception
  # @author CuongCT
  # Create Date: 2014/12/17
  # Modify Date:
  # PATCH/PUT /curriculums/1
  # PATCH/PUT /curriculums/1.json
  def quickupdate
    begin
      # @material = Material.new(curriculum_params)
      # if !@material.update_attributes(:material_name => @material.material_name, :material_type => @material.material_type_id, :material_url => @material.material_url, :description => @material.description)
      #   respond_to do |format|
      #     flash.now[:error] = t('comments.msg_reply_fail')
      #     format.js { render action: 'reply_fail' }
      #     #format.html
      #   end
      # end
      material_id = BSON::ObjectId.from_string(params[:material][:id])
      material = Material.find_by(:id => material_id)
      if material.nil?
        # if !material.save
        #   respond_to do |format|
        #     if material.errors
        #       flash.now[:error] = material.errors.full_messages.to_sentence(:last_word_connector => ', ')
        #     else
        #       flash.now[:error] = t('material.msg_update_failed')
        #     end
        #     format.js { render partial: 'layouts/error' }
        #     # format.html
        #   end
        # end
        # response
        flash.now[:error] = t('material.msg_not_found')
        respond_to do |format|
          format.js { render partial: 'mentor/error' }
          # format.html
        end
      else
        if !material.update_attributes(:material_name => params[:material][:material_name],:material_url => params[:material][:material_url], :description => params[:material][:description],:material_type => params[:material][:material_type_id])
          respond_to do |format|
            if material.errors
              flash.now[:error] = material.errors.full_messages.to_sentence(:last_word_connector => ', ')
            else
              flash.now[:error] = t('material.msg_update_failed')
            end
            format.js { render partial: 'mentor/error' }
            # format.html
          end
        else
          # response
          respond_to do |format|
            flash.now[:notice] = t('material.msg_update_success')
            format.js { render partial: 'mentor/success'}
            # format.html
          end
        end
      end
    rescue Exception => e
      logger.error("Material save error: #{e.message}")
      respond_to do |format|
        flash.now[:error] = t('material.msg_update_failed')
        format.js { render partial: 'mentor/error' }
        # format.html
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url, notice: 'Material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  def curriculum_params
    params.require(:material).permit(:id, :material_name, :material_type_id, :material_url, :description)
  end
end

app/views/materials/_edit.js.erb
$('#modalContent').html('<%= escape_javascript(render(:partial  => 'materials/form', locals: {material: @material})) %>')

app/views/materials/_form.html.erb
<%= form_for @material,:url => '/materials/quickupdate', html: {id: 'quick_form', method:'path', role: 'form',class:'form-horizontal'} do |f| %>
  <div class="widget ">
    <div class="widget-body">
      <div  id="panelmaterial" class="innerLR">
        <div class="material" id="material<%=@material.id%>" >
          <input name="material_id" value="<%=@material.id%>" type=hidden>
          <div class="form-group" >
            <label for="material_name" class="col-md-2 control-label"><%= t('material.lb_material_name') %><span class="requiredfield">*</span></label>
            <div class="col-md-10">
              <%= f.hidden_field :id, class: "form-control"%>
              <%= f.text_field :material_name, class: "form-control requiredfield100 name_update", placeholder: t('material.lb_material_name'),maxlength:100,autofocus:"autofocus" %>
            </div>
          </div>
          <div class="form-group" >
            <label for="material_type_id" class="col-md-2 control-label"><%= t('material.lb_type') %></label>
            <div class="col-md-10">
              <%= select_tag "material[material_type_id]", options_from_collection_for_select(MaterialType.all, "id", "material_type_name",@material.material_type.id),{ class: 'selectpicker form-control type_update' } %>
            </div>
          </div>
          <div class="form-group" >
            <label for="material_url" class="col-md-2 control-label"><%= t('material.lb_url') %></label>
            <div class="col-md-10">
              <%= f.text_field :material_url, class: "form-control urlformat url_update", placeholder: t('material.lb_url'),maxlength:500 %>
            </div>
          </div>
          <div class="form-group" >
            <label for="description" class="col-md-2 control-label"><%= t('material.lb_description') %></label>
            <div class="col-md-10">
              <%= f.text_area "description", class: 'form-control summernote summernoteMaterial description_update' , placeholder: t('material.lb_description'),rows:2 %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


<script>
    $('.summernoteMaterial').summernote({
        lang: 'ja-JP',
        height: 100,
        onblur: function(e) {
            var content = $(this).html();
            var SCRIPT_REGEX = /&lt;script\b[^<]*(?:(?!&lt;\/script&gt;)<[^<]*)*&lt;\/script&gt;/gi;
            content = content.replace(SCRIPT_REGEX,"");
            $(this).parent("div.note-editor").siblings("textarea.summernoteMaterial").html(content);
            $(this).html(content)
        }
    });
    $('.selectpicker').selectpicker({
        size: 10
    });

    $.validator.messages.required = "<%= t('js.validate.msg_required')%>";
    $.validator.messages.url = "<%= t('js.validate.msg_url_invalid')%>";
    $.validator.messages.maxlength = "<%= t('js.validate.msg_maxlength')%>";
    $.validator.addMethod("validSummernote", function(value, element) {
        return this.optional(element) || !(value.length>10000);
    }, "<%= t('curriculum.msg_description_maxlength')%>");
    $.validator.addClassRules("requiredfield100", {
        maxlength:100,
        required: {
            depends:function(){
                var text = $.trim($(this).val());
                text=text.replace(/\s+/g, ' ');
                $(this).val(text);
                return true;
            }
        }
    });
    $.validator.addClassRules("urlformat", {
        url: true,
        maxlength:500
    });

    $.validator.addClassRules("summernote", {
        validSummernote: true
    });
    $("#quick_form").validate({
        ignore: ':hidden:not("textarea.summernote")', //ignore fields
        onfocusout: false,
        onkeyup: false,
        errorPlacement: function (error, element) {
            error.insertAfter(element);
        },
        submitHandler: function (form) {
//            $('#signup_form').find('input:text').each(function(){
//                $(this).val($.trim($(this).val()));
//            });
//            form.submit();

        },
        invalidHandler: function(form, validator) {
            $('#div_msg_error').text('');

            var errors = validator.numberOfInvalids();
            if (errors) {
                validator.errorList[0].element.focus();
            }
        }
    });
</script>
<% end %>

app/views/materials/edit.html.erb
<h1>Editing material</h1>

<%= render 'form' %>

<%= link_to 'Show', @material %> |
<%= link_to 'Back', materials_path %>

app/views/materials/index.html.erb
<h1>Listing materials</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= link_to 'Show', material %></td>
        <td><%= link_to 'Edit', edit_material_path(material) %></td>
        <td><%= link_to 'Destroy', material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Material', new_material_path %>

app/views/materials/new.html.erb
<h1>New material</h1>

<%= render 'form' %>

<%= link_to 'Back', materials_path %>

app/views/materials/show.html.erb
<div class="row  row-offcanvas row-offcanvas-right" >
  <!--Left Column-->
  <div class="col-xs-12 col-md-9">
    <div class="widget media-body">
      <p class="pull-right visible-xs">
        <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas"><%= t('curriculum.lb_curriculum_outline')%> </button>
      </p>
      <div class="aes-jumbotron"  id="divContent">
        <h4 ><%= link_to @curriculum.curriculum_name, curriculum_path(@curriculum)%></h4>
        <p><span><i class="fa fa-user">&nbsp;</i><%= @curriculum.mentor.user_name %></span>&nbsp;|&nbsp;<span><i class="fa fa-calendar">&nbsp;</i><%= @curriculum.created_at.strftime("%Y/%m/%d") %></span></p>
        <div class="separator"></div>
        <h4 class="aes-border-bottom "><%= t('material.title_material')%> - <%=@material.material_name%></h4>
        <p>
          <%= !(@material.material_type == nil)? @material.material_type.material_type_name: nil%>
        </p>
        <%if !@material.material_url.nil? && !@material.material_url.empty?%>
            <p>
              <span class="strong"><%=t('material.lb_url')%></span>: <a href="<%= @material.material_url%>"><%= @material.material_url%></a>
            </p>
        <% end %>
        <div class="aes-content" ><%= sanitize @material.description %></div>
      </div>
    </div>
    <div class="widget media-body">
      <!--Comment-->
      <div id='divComments'>
        <%= render 'comments/comments' %>
      </div>
      <!--End comment-->
    </div>
  </div>
  <!--End left column-->
  <div class="col-xs-6 col-md-3 sidebar-offcanvas" id="sidebar" role="navigation">
    <!--Right Column-->
    <div id="divRight" class="widget media-body">
      <div class="innerAll menu-right">
        <div>
          <h4 class="aes-border-bottom strong"><%= t('material.title_material')%></h4>
          <ul class="fa-ul" >
            <% @materials.each do |material| %>
                <li>
                  <i class="fa-li fa fa-square"></i><%= material.material_name %>
                  <ul class="fa-ul">
                    <% material.children.each do |child| %>
                        <li><i class="fa-li fa fa-square"></i><%= child.material_name %></li>
                    <%end%>
                  </ul>
                </li>
            <%end%>
          </ul>
        </div>
        <!--Edd Material-->
        <!--Action-->
        <div>
          <h4 class="aes-border-bottom strong"><%= t('action.title_action')%></h4>
          <ul class="fa-ul">
            <% @curriculum.actions.each do |action| %>
                <li><i class="fa-li fa fa-square"></i><%= action.action_name %></li>
            <%end%>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- // End right column  -->
</div>
<script type="text/javascript">
    $(document).ready(function () {
            $('#divRight a').removeClass("strong");
            $("#<%= @material.id %>").addClass("strong");
        });
</script>