config/routes.rb
Rails.application.routes.draw do
  resources :educations

  get 'aes_actions/quickedit'
  patch 'aes_actions/quickupdate'

  patch 'materials/quickupdate'
  get 'materials/quickedit'

  patch 'curriculums/quickupdatecategories'
  get 'curriculums/quickeditcategories'

  patch 'curriculums/quickupdate'
  get 'curriculums/quickedit'

  get 'work_experiences/update_levels'
  resources :work_experiences

  match 'actions/:id', to: 'aes_actions#show', via: [:get],  as: 'aes_action_show'
  resources :materials
  get 'users/about'
  match 'about/:id', to: 'users#about', via: [:get],  as: 'about'
  get 'users/show'
  post 'users/send_mail'

  get 'users/changepassword'
  post 'users/changepassword'

  get 'roadmap/get_more_roadmap'
  get 'roadmap/index'
  post 'roadmap/create'
  post 'roadmap/delete'
  post 'roadmap/update'
  get 'roadmap/update_levels'

  get '/comments/get_more_comments'
  get 'comments/index'


  get 'comments/new'

  get 'comments/create'
  post 'comments/create'

  get 'comments/reply'
  post 'comments/reply'




  get 'comment/update'

  get 'comment/destroy'

  get 'home/error'

  get 'curriculums/get_material_types'
  get 'curriculums/update_content'
  get 'curriculums/getlevel'
  resources :aes_actions
  resources :materials
  resources :curriculums
  match 'curriculums/join/:id', to: 'curriculums#join', via: [:get],  as: 'join_curriculum'
  match 'curriculums/comment/:id', to: 'curriculums#comment', via: [:get],  as: 'comments_curriculum'
  match 'curriculums/materials/:id', to: 'curriculums#materials', via: [:get],  as: 'materials_curriculum'
  match 'curriculums/actions/:id', to: 'curriculums#actions', via: [:get],  as: 'actions_curriculum'
  match 'curriculums/mentordetail/:id', to: 'curriculums#show_for_mentor', via: [:get],  as: 'show_curriculum_for_mentor'

  get 'student/update_curriculum_detail', as: 'update_curriculum_detail'
  get 'student/update_menu_right', as: 'update_menu_right'
  match 'student/curriculum-detail/:id', to: 'student#show', via: [:get],  as: 'show_curriculum_detail_for_student'

  get 'mentor/update_curriculum_detail', as: 'mentor_update_curriculum_detail'
  match 'mentor/curriculum-detail/:id', to: 'mentor#show', via: [:get],  as: 'show_curriculum_detail_for_mentor'


  get 'home/index'

  get 'mentor/index'
  get 'student/index'
  get 'mentor/create'

  get 'search/index'
  get 'search/search_curriculum'
  get 'search/update_levels', as: 'update_levels'
  match 'search-curriculum', :to => 'search#search_curriculum', :via => [:get], :as => 'search-curriculum'

  match 'signup', :to => 'sessions#signup', :via => [:get, :post], :as => 'signup'
  match 'signin', :to => 'sessions#signin', :via => [:get, :post], :as => 'signin'
  match 'signout', :to => 'sessions#signout', :via => [:get, :post], :as => 'signout'
  match 'welcome', :to => 'home#welcome', :via =>[:get], :as => 'welcome'
  match 'about-us', :to => 'home#about_us', :via =>[:get], :as => 'about_us'
  match 'home', :to => 'home#index', :via => [:get], :as => 'home'

  match 'become_mentor', :to => 'student#become_mentor', :via => [:get, :post], :as => 'become_mentor'



  get 'sessions/signin'

  get 'sessions/signup'

  get 'sessions/signout'



  root 'sessions#signin'

  get '/auth/:provider/callback', to: 'sns_sessions#create'
  get '/auth/failure', to: redirect('/')
  get 'sns_sessions/create'

  match 'signup_sns', :to => 'sns_sessions#signup_sns', :via => [:get, :post], :as => 'signup_sns'
  get 'sns_sessions/signup_sns'

  get 'sns_sessions/signin_sns'

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all










end

app/models/education.rb
# Class Name: Education
# Description: educations model class
# Version: 1.0
# Copyright: Telsoft
# Author: HuyenDT
# Create Date: 23/12/2014
# Modify Date:

class Education
  include Mongoid::Document
  include Mongoid::Timestamps

  SCHOOL_NAME_MAX_LENGTH = 200
  DESCRIPTION_MAX_LENGTH = 200

  field :school_name, type: String
  field :start_year, type: Integer
  field :end_year, type: Integer
  field :current, type: Boolean
  field :description, type: String

  #relations
  # belongs_to :field, class_name: 'Category', foreign_key: :field_id
  belongs_to :user

  #indexs
  index({user_id: 1})

  #validates
  validates_presence_of :user
  validates_presence_of :school_name
  validates_length_of :school_name, maximum: SCHOOL_NAME_MAX_LENGTH
  validates_presence_of :start_year
  validates_numericality_of :start_year, only_integer: true, greater_than_or_equal_to: 1905, less_than_or_equal_to: Time.now.year
  validates_numericality_of :end_year, only_integer: true, greater_than_or_equal_to: 1905, less_than_or_equal_to: Time.now.year, allow_blank: true
  validates_length_of :description, maximum: DESCRIPTION_MAX_LENGTH

  validate :validate_years

  def validate_years
    if self.current
      self.end_year = nil
    end

    if !self.start_year.nil? && !self.end_year.nil? && end_year < start_year
      errors.add(:end_year, :greater_than_or_equal_to, :count => self.start_year)
    end
  end
end


app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  layout 'default'
  before_action :authenticate
  before_action :set_education, only: [:show, :edit, :update, :destroy]

  # GET /educations
  # GET /educations.json
  def index
    user_id = session[:user_id]
    @educations = Education.where(user_id: user_id).order_by(created_at: -1)
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
  end

  # GET /educations/new
  def new
    @education = Education.new
  end

  # GET /educations/1/edit
  def edit
    if @education.nil?
      flash.now[:error] = t('educations.msg_education_not_found')
      respond_to do |format|
        format.js { render action: 'edit_fail', :not_found => true }
      end
    end
  end

  # POST /educations
  # POST /educations.json
  def create
    @education = Education.new(education_params)
    @education.user_id = session[:user_id]

    respond_to do |format|
      if @education.save
        flash.now[:notice] = t('educations.msg_create_successfully')
        format.html { redirect_to @education, notice: t('educations.msg_create_successfully') }
        format.json { render :show, status: :created, location: @education }
        format.js
      else
        if @education.errors
          flash.now[:error] = @education.errors.full_messages.to_sentence(:last_word_connector => ', ');
        else
          flash.now[:error] = t('educations.msg_create_fail')
        end
        format.html { render :new }
        format.json { render json: @education.errors, status: :unprocessable_entity }
        format.js { render action: 'create_fail' }
      end
    end
  end

  # PATCH/PUT /educations/1
  # PATCH/PUT /educations/1.json
  def update
    if @education.nil?
      flash.now[:error] = t('educations.msg_education_not_found')
      respond_to do |format|
        format.js { render action: 'update_fail' }
      end
    else
      respond_to do |format|
        if @education.update(education_params)
          format.html { redirect_to @education, notice: t('educations.msg_update_successfully')}
          format.json { render :show, status: :ok, location: @education }
          format.js
        else
          if @education.errors
            flash.now[:error] = @education.errors.full_messages.to_sentence(:last_word_connector => ', ');
          else
            flash.now[:error] = t('educations.msg_update_fail')
          end
          format.html { render :edit }
          format.json { render json: @education.errors, status: :unprocessable_entity }
          format.js { render action: 'update_fail' }
        end
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    if @education.nil?
      flash.now[:error] = t('educations.msg_education_not_found')
      respond_to do |format|
        format.js {render action: 'destroy_fail'}
      end
    else
      if @education.destroy
        respond_to do |format|
          format.html { redirect_to educations_url, notice: t('educations.msg_delete_successfully') }
          format.json { head :no_content }
          format.js
        end
      else
        if @education.errors
          flash.now[:error] = @education.errors.full_messages.to_sentence(:last_word_connector => ', ');
        else
          flash.now[:error] = t('educations.msg_update_fail')
        end

        respond_to do |format|
          format.js {render action: 'destroy_fail'}
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_params
      if params[:education][:school_name]
        params[:education][:school_name] = params[:education][:school_name].strip
      end

      if params[:education][:description]
        params[:education][:description] = params[:education][:description].strip
      end
      params.require(:education).permit(:school_name, :start_year, :end_year, :current, :description)
    end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_form.html.erb
<%= form_for(@education) do |f| %>
  <% if @education.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@education.errors.count, "error") %> prohibited this education from being saved:</h2>

      <ul>
      <% @education.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :school_name %><br>
    <%= f.text_field :school_name %>
  </div>
  <div class="field">
    <%= f.label :start_year %><br>
    <%= f.number_field :start_year %>
  </div>
  <div class="field">
    <%= f.label :end_year %><br>
    <%= f.number_field :end_year %>
  </div>
  <div class="field">
    <%= f.label :current %><br>
    <%= f.check_box :current %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/educations/_form_education.html.erb
<%= form_for @education, html: {id: 'education_form', role: 'form'} do |f| %>
    <div class="widget ">
      <div class="widget-body">
        <div id="paneleducation" class="innerLR">
          <div class="education" id="<%= @education.id %>">
            <div class="form-group">
              <%= f.text_field :school_name, maxlength: 200, class: 'form-control', placeholder: t('educations.placeholder_school_name') %>
            </div>

            <div class="form-group">
                <div class="checkbox">
                  <label class="checkbox-custom">
                    <%= f.check_box :current%><i class="fa fa-fw fa-square-o" style="margin-left: -13px;"></i> <%= t('educations.lb_current') %>
                  </label>
                </div>
            </div>

            <div class="form-group">
              <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                  <%= f.select :start_year, year_options_for_select, {:include_blank => t('educations.placeholder_start_year')}, {class: "form-control"} %>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6">
                  <%= f.select :end_year, year_options_for_select, {:include_blank => t('educations.placeholder_end_year')},  {class: "form-control"}%>
                </div>
              </div>
            </div>

            <div class="form-group">
                <%= f.text_area :description, maxlength: 200, class: 'form-control', placeholder: t('educations.placeholder_description'), rows: 2 %>
            </div>
        </div>
      </div>
    </div>
    </div>

<% end %>

<script>
    $(document).ready(function () {
        $('.checkbox-custom > input[type=checkbox]').each(function () {
            var $this = $(this);
            if ($this.data('checkbox')) return;
            $this.checkbox($this.data());
        });

        if ($("#education_current").attr('checked') == 'checked') {
            $("#education_end_year").val('');
            $("#education_end_year").prop('disabled',true);
        }

        $("#education_current").change(function() {
            if(this.checked) {
                $("#education_end_year").val('');
                $("#education_end_year").prop('disabled',true);
            } else {
                $("#education_end_year").prop('disabled',false);
            }
        });

    });
</script>

app/views/educations/_new_education.html.erb
<div class="innerAll border-bottom" id="education_new">
  <div class="row">
    <div class="col-sm-10">
      <ul class="media-list margin-none">
        <li class="media">
          <span class="pull-left innerAll half empty-photo">
          <a class="education btn btn-xs" url="<%= new_education_path %>"  href="#" data-toggle="modal"  modal_title="<%=t('educations.title_new_education')%>">
            <i class="fa fa-plus fa-2x text-muted"></i>
          </a>
            </span>
          <div class="media-body innerAll half">

            <span class="media-heading">
              <a class="education" url="<%= new_education_path %>"  href="#" data-toggle="modal"  modal_title="<%=t('educations.title_new_education')%>">
                <%= t('educations.title_new_education')%>
              </a>
            </span>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/educations/create.js.erb
$('#educations_list').prepend('<%= escape_javascript(render partial: @education) %>');
//notyfy({
//    text: '<%= flash[:notice]%>',
//    type: 'alert',
//    dismissQueue: false,
//    layout: 'top',
//    timeout: 5000 // delay for closing event. Set false for sticky notifications
//});
$('#educationModal').modal('hide');

var editElement = $('#education<%= @education.id %>').find(".editEducation");
$(editElement).bind('click', function (e) {
    openEditEducationModal(this, e);
});

var deleteElement = $('#education<%= @education.id %>').find(".deleteEducation");
$(deleteElement).bind('click', function (e) {
    processDeleteEducation(this, e);
});

app/views/educations/create_fail.js.erb
$.gritter.add({
    title: '<%= t('system.system_message') %>',
    text: '<%= flash[:error]%>',
    before_open: function(){
        if($('.gritter-item-wrapper').length == 1)
        {
            return false;
        }
    }
});

app/views/educations/destroy.js.erb
$('#education<%= @education.id %>').remove();

app/views/educations/destroy_fail.js.erb
$.gritter.add({
    title: '<%= t('system.system_message') %>',
    text: '<%= flash[:error]%>',
    before_open: function(){
        if($('.gritter-item-wrapper').length == 1)
        {
            return false;
        }
    }
});

app/views/educations/edit.html.erb
<h1>Editing education</h1>

<%= render 'form' %>

<%= link_to 'Show', @education %> |
<%= link_to 'Back', educations_path %>

app/views/educations/edit_fail.js.erb
$.gritter.add({
    title: '<%= t('system.system_message') %>',
    text: '<%= flash[:error]%>',
    before_open: function(){
        if($('.gritter-item-wrapper').length == 1)
        {
            return false;
        }
    }
});



app/views/educations/new.html.erb
<h1>New education</h1>

<%= render 'form' %>

<%= link_to 'Back', educations_path %>

app/views/educations/new.js.erb
$('#modalContent').html('<%= escape_javascript(render(:partial  => 'educations/form_education', locals: {education: @education})) %>')

app/views/educations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>School name:</strong>
  <%= @education.school_name %>
</p>

<p>
  <strong>Start year:</strong>
  <%= @education.start_year %>
</p>

<p>
  <strong>End year:</strong>
  <%= @education.end_year %>
</p>

<p>
  <strong>Current:</strong>
  <%= @education.current %>
</p>

<p>
  <strong>Description:</strong>
  <%= @education.description %>
</p>

<%= link_to 'Edit', edit_education_path(@education) %> |
<%= link_to 'Back', educations_path %>

app/views/educations/update.js.erb
$('#education<%= @education.id %>').replaceWith('<%= escape_javascript(render partial: @education) %>');
//notyfy({
//    text: '<%= flash[:notice]%>',
//    type: 'alert',
//    dismissQueue: false,
//    layout: 'top',
//    timeout: 5000 // delay for closing event. Set false for sticky notifications
//});
$('#educationModal').modal('hide');

var editElement = $('#education<%= @education.id %>').find(".editEducation");
$(editElement).bind('click', function (e) {
    openEditEducationModal(this, e)
});

var deleteElement = $('#education<%= @education.id %>').find(".deleteEducation");
$(deleteElement).bind('click', function (e) {
    processDeleteEducation(this, e);
});

app/views/educations/update_fail.js.erb
$.gritter.add({
    title: '<%= t('system.system_message') %>',
    text: '<%= flash[:error]%>',
    before_open: function(){
        if($('.gritter-item-wrapper').length == 1)
        {
            return false;
        }
    }
});